---

- name: Create swapfile {{ freebsd_postinstall_swap_file }}
  shell: sh -c 'if [ ! -e {{ freebsd_postinstall_swap_file }} ]; then printf "create"; fi'
  register: command_result
  changed_when: command_result.stdout == "create"
  notify: create and mount swap
  when: freebsd_postinstall_swap|lower == "yes"
  tags: fp_create_mount_swap_file

- name: Change swapfile {{ freebsd_postinstall_swap_file }}
  shell: sh -c 'if [ -e {{ freebsd_postinstall_swap_file }} ] && [ "`stat -f %z {{ freebsd_postinstall_swap_file }}`" -ne "{{ freebsd_postinstall_swap_stsize }}" ]; then printf "change"; fi'
  register: command_result
  changed_when: command_result.stdout == "change"
  notify: change and mount swap
  when: freebsd_postinstall_swap|lower == "yes"
  tags: fp_change_mount_swap_file
  
- name: Create swap entry in /etc/fstab
  lineinfile: >
    dest="/etc/fstab"
    regexp="{{ freebsd_postinstall_swap_file }}"
    line="{{ freebsd_postinstall_swap_md }} none swap sw,file={{ freebsd_postinstall_swap_file }},late 0 0"
    backup="yes"
  notify: create and mount swap
  when: freebsd_postinstall_swap|lower == "yes"
  tags: fp_mount_swap_file

- name: Remove swap entry from /etc/fstab
  lineinfile: >
    dest="/etc/fstab"
    regexp="{{ freebsd_postinstall_swap_file }}"
    line="{{ freebsd_postinstall_swap_md }} none swap sw,file={{ freebsd_postinstall_swap_file }},late 0 0"
    backup="yes"
    state="absent"
# notify: umount swap
  when: freebsd_postinstall_swap|lower == "no"
  tags: fp_umount_swap_file

# EOF
...
