---

- name: Configure hostname in /etc/rc.conf
  lineinfile: >
    dest="/etc/rc.conf"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    backup="yes"
  with_items:
    - { regexp: "^hostname",  line: "hostname=\"{{ rc_conf_hostname }}\""}
  notify: set hostname
  tags:
    - fp_hostname_rcconf
    - fp_hostname
    - fp_all

# DO overwrites hostname from rc.conf
- name: Configure hostname in /etc/rc.digitalocean.d/droplet.conf
  lineinfile: >
    dest="/etc/rc.digitalocean.d/droplet.conf"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    backup="yes"
  with_items:
    - { regexp: "^hostname",  line: "hostname=\"{{ rc_conf_hostname }}\""}
  when:
    - digitalocean|lower == "yes"
    - ansible_distribution_major_version < '11'
  tags:
    - fp_hostname_rcconf_digitalocean
    - fp_hostname_rcconf
    - fp_hostname
    - fp_all

# EOF
...
