---

- name: Create .forward files
  command: sh -c "if [ ! -e /home/{{ item.user }}/.forward ]; then touch /home/{{ item.user }}/.forward; chown '{{ item.user }}' /home/{{ item.user }}/.forward; chmod 0644 /home/{{ item.user }}/.forward; fi"
  with_items: "{{ freebsd_postinstall_procmail_forwarders }}"
  changed_when: false
  tags:
    - fp_procmail_forward
    - fp_procmail
    - fp_all

- name: Configure forwarders
  blockinfile:
    dest: "/home/{{ item.user }}/.forward"
    backup: "yes"
    create: "yes"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      "{{ item.forward }}"
  with_items: "{{ freebsd_postinstall_procmail_forwarders }}"
  when: freebsd_postinstall_procmail_install|lower == "yes"
  tags:
    - fp_procmail_forwarders
    - fp_procmail
    - fp_all

- name: Create .procmailrc files
  command: sh -c "if [ ! -e /home/{{ item.user }}/.procmailrc ]; then touch /home/{{ item.user }}/.procmailrc; chown '{{ item.user }}' /home/{{ item.user }}/.procmailrc; chmod 0644 /home/{{ item.user }}/.procmailrc; fi"
  with_items: "{{ freebsd_postinstall_procmail_forwarders }}"
  changed_when: false
  tags:
    - fp_procmail_procmailrc
    - fp_procmail
    - fp_all

- name: Configure .procmailrc
  blockinfile:
    dest: "/home/{{ item.user }}/.procmailrc"
    backup: "yes"
    create: "yes"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      SHELL={{ freebsd_postinstall_procmail_shell }}
      VERBOSE={{ freebsd_postinstall_procmail_verbose }}
      PATH={{ freebsd_postinstall_procmail_path }}
      MAILDIR={{ freebsd_postinstall_procmail_maildir }}
      DEFAULT=/var/mail/{{ item.user }}
      PMDIR={{ freebsd_postinstall_procmail_pmdir }}
      LOGFILE=$PMDIR/pm.log
      LOCKFILE=$PMDIR/.lockfile
      SENDMAIL=/usr/sbin/sendmail
  with_items: "{{ freebsd_postinstall_procmail_forwarders }}"
  tags:
    - fp_procmail_procmailrc
    - fp_procmail
    - fp_all

- name: Create .procmail directory
  file: >
    path="/home/{{ item.user }}/.procmail"
    state="directory"
    owner="{{ item.user }}"
  with_items: "{{ freebsd_postinstall_procmail_forwarders }}"
  tags:
    - fp_procmail_dir
    - fp_procmail
    - fp_all

- name: Create includerc files
  template: >
    src="procmailrc-includerc-{{ item.template }}.j2"
    dest="/home/{{ item.user }}/.procmail/{{ item.template }}.rc"
    backup="yes"
  with_items: "{{ freebsd_postinstall_procmail_includerc }}"
  tags:
    - fp_procmail_includerc
    - fp_procmail
    - fp_all

- name: Include rc files in .procmailrc
  lineinfile: >
    dest="/home/{{ item.user }}/.procmailrc"
    line="INCLUDERC=$PMDIR/{{ item.template }}.rc"
    insertafter="EOF"
    backup="yes"
  with_items: "{{ freebsd_postinstall_procmail_includerc }}"
  tags:
    - fp_procmail_includerc
    - fp_procmail
    - fp_all

# EOF
...
