---

- name: Copy ntp.conf template file
  template: >
    src="ntp.conf.j2"
    dest="/etc/ntp.conf"
    backup="yes"
  notify:
    - restart ntp
  tags:
    - freebsd_postinstall_ntp_conf

- name: Start/stop ntp service
  service: >
    name="{{ ntp_service_name }}"
    state="{{ ntp_service_state }}"
    enabled="{{ ntp_service_enabled }}"
    pattern="/ntpd"
  tags:
    - freebsd_postinstall_ntp_start
