---

- name: Configure ntpdate in /etc/rc.conf
  lineinfile: >
    dest="/etc/rc.conf"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    backup="yes"
  with_items:
    - { regexp: "^ntpdate_enable",  line: "ntpdate_enable=\"{{ ntpdate_enable }}\""}
    - { regexp: "^ntpdate_flags",  line: "ntpdate_flags=\"{{ ntpdate_flags }}\""}
    - { regexp: "^ntpd_sync_on_start",  line: "ntpd_sync_on_start=\"{{ ntpd_sync_on_start }}\""}
  tags:
    - fp_ntpdate
    - fp_all

# EOF
...
