---

- name: Configure /etc/libmap.conf
  lineinfile: >
    dest="/etc/libmap.conf"
    regexp="^{{ item.origin }} "
    line="{{ item.origin }} {{ item.target }}"
    backup="yes"
  with_items: "{{ freebsd_postinstall_libmap_entries }}"
  when: freebsd_postinstall_libmap_entries > 0
  tags:
    - fp_libmap
    - fp_all

# EOF
...
