---

- name: Enable and start hostapd
  lineinfile: >
    dest="/etc/rc.conf"
    regexp="^hostapd_enable"
    line="hostapd_enable=\"YES\""
    backup="yes"
  notify: enable and start hostapd
  when: freebsd_postinstall_hostapd_enabled == "YES"
  tags: config_rc_conf_smart

- name: Disable and stop hostapd
  lineinfile: >
    dest="/etc/rc.conf"
    regexp="^hostapd_enable"
    line="hostapd_enable=\"NO\""
    backup="yes"
  notify: disable and stop hostapd
  when: freebsd_postinstall_hostapd_enabled == "NO"
  tags: config_rc_conf_smart

- name: Configure interface for hostapd
  lineinfile: >
    dest="/etc/rc.conf"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    backup="yes"
  with_items:
    - { regexp: "^create_args_{{freebsd_postinstall_hostapd_interface}}",
        line: "create_args_{{freebsd_postinstall_hostapd_interface}}=\"wlanmode hostap country {{freebsd_postinstall_hostapd_country}}\""}
    - { regexp: "^wlans_{{freebsd_postinstall_hostapd_device}}",
        line: "wlans_{{freebsd_postinstall_hostapd_device}}=\"{{freebsd_postinstall_hostapd_interface}}\"" }
    - { regexp: "^ifconfig_{{freebsd_postinstall_hostapd_interface}}",
        line: "ifconfig_{{freebsd_postinstall_hostapd_interface}}=\"inet {{freebsd_postinstall_hostapd_inet}} netmask {{freebsd_postinstall_hostapd_netmask}}\"" }
  notify: restart hostapd
  when: freebsd_postinstall_hostapd_enabled == "YES"
  tags: config_rc_conf_smart
  
- name: Copy hostapd.conf template file
  template: >
    src="hostapd.conf.j2"
    dest="/etc/hostapd.conf"
    backup="yes"
  notify: restart hostapd
  when: freebsd_postinstall_hostapd_enabled == "YES"
  tags: freebsd_postinstall_hostapd_conf
