---

- name: Create swapfile {{freebsd_postinstall_swap_file}}
  shell: sh -c 'if [ ! -e {{freebsd_postinstall_swap_file}} ]; then printf "create"; fi'
  register: command_result
  changed_when: command_result.stdout == "create"
  notify: create and mount swap
  tags: create_mount_swap_file

- name: Change swapfile {{freebsd_postinstall_swap_file}}
  shell: sh -c 'if [ -e {{freebsd_postinstall_swap_file}} ] && [ "`stat -f %z {{freebsd_postinstall_swap_file}}`" -ne "{{freebsd_postinstall_swap_stsize}}" ]; then printf "change"; fi'
  register: command_result
  changed_when: command_result.stdout == "change"
  notify: change and mount swap
  tags: change_mount_swap_file
  
- name: Create swap entry in /etc/fstab
  lineinfile: >
    dest="/etc/fstab"
    regexp="{{freebsd_postinstall_swap_file}}"
    line="{{freebsd_postinstall_swap_md}} none swap sw,file={{freebsd_postinstall_swap_file}},late 0 0"
    backup="yes"
  notify: create and mount swap
  tags: mount_swap_file
