---

- name: Add or update users
  user: >
    name="{{ item.name }}"
    shell="{{ item.shell }}"
    password="{{ item.password }}"
    update_password="{{ item.update_password }}"
  with_items: "{{ freebsd_users }}"
  tags:
    - fp_users
    - fp_all

- name: Add users to additional groups
  user: >
    name="{{ item.name }}"
    groups="{{ item.groups }}"
    append="yes"
  with_items: "{{ freebsd_users_groups }}"
  tags:
    - fp_groups
    - fp_all

# EOF
...
