---

- name: Enable and start apcupsd
  lineinfile: >
    dest="/etc/rc.conf"
    regexp="^apcupsd_enable"
    line="apcupsd_enable=\"YES\""
    backup="yes"
  when: freebsd_postinstall_apcupsd_service_enabled|lower == "yes"
  notify: enable and start apcupsd
  tags: fp_rc_conf_apcupsd

- name: Disable and stop apcupsd
  lineinfile: >
    dest="/etc/rc.conf"
    regexp="^apcupsd_enable"
    line="apcupsd_enable=\"NO\""
    backup="yes"
  when: freebsd_postinstall_apcupsd_service_enabled|lower == "no"
  notify: disable and stop apcupsd
  tags: fp_rc_conf_apcupsd

- name: Configure apcupsd.conf
  template: >
    src="apcupsd.conf.j2"
    dest="{{ freebsd_postinstall_apcupsd_conf_file }}"
    create="yes"
    owner="{{ freebsd_postinstall_apcupsd_conf_owner }}"
    group="{{ freebsd_postinstall_apcupsd_conf_group }}"
    mode="{{ freebsd_postinstall_apcupsd_conf_mode }}"
    backup="yes"
  when: freebsd_postinstall_apcupsd_service_enabled|lower == "yes"
  notify: restart apcupsd
  tags:
    - fp_apcupsd_conf

# EOF
...
