---

- name: Enable and start smartd
  lineinfile: >
    dest="/etc/rc.conf"
    regexp="^smartd_enable"
    line="smartd_enable=\"YES\""
    backup="yes"
  when:
    - freebsd_postinstall_smartd_service_enabled|lower == "yes"
    - freebsd_postinstall_smartd_install|lower == "yes"
  notify: enable and start smartd
  tags: fp_rc_conf_smartd

- name: Disable and stop smartd
  lineinfile: >
    dest="/etc/rc.conf"
    regexp="^smartd_enable"
    line="smartd_enable=\"NO\""
    backup="yes"
  when:
    - freebsd_postinstall_smartd_service_enabled|lower == "no"
    - freebsd_postinstall_smartd_install|lower == "yes"
  notify: disable and stop smartd
  tags: fp_rc_conf_smartd

- name: Configure smartd.conf
  lineinfile: >
    dest="{{ freebsd_postinstall_smartd_conf_file }}"
    regexp="^DEVICESCAN"
    state="absent"
    backup="yes"
  notify: reload smartd
  tags: fp_smartd_conf

- name: Configure devices in {{ freebsd_postinstall_smartd_conf_file }}
  lineinfile: >
    dest="{{ freebsd_postinstall_smartd_conf_file }}"
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    create="yes"
    owner="{{ freebsd_postinstall_smartd_conf_owner }}"
    group="{{ freebsd_postinstall_smartd_conf_group }}"
    mode="{{ freebsd_postinstall_smartd_conf_mode }}"
    backup="yes"
  with_items: "{{ freebsd_postinstall_smartd_devices }}"
  notify: reload smartd
  tags: fp_smartd_conf

# EOF
...
