---

- name: Configure {{ ssh_config_path }}
  lineinfile: >
    dest="{{ ssh_config_path }}"
    regexp="^{{ item.key }}"
    insertbefore="^{{'#'}}{{ item.key }}"
    line="{{ item.key }} {{ item.value }}"
    backup="yes"
  with_items: "{{ ssh_config }}"
  tags:
    - fp_ssh_config
    - fp_ssh
    - fp_all

- name: Configure {{ sshd_config_path }}
  lineinfile: >
    dest="{{ sshd_config_path }}"
    regexp="^{{ item.key }}"
    insertbefore="^{{'#'}}{{ item.key }}"
    line="{{ item.key }} {{ item.value }}"
    backup="yes"
    validate="{{ sshd_path }} -t -f %s"
  with_items: "{{ sshd_config }}"
  notify: reload sshd
  tags:
    - fp_ssh_sshd_config
    - fp_ssh
    - fp_all

- name: Enable and start sshd
  lineinfile: >
    dest="/etc/rc.conf"
    regexp="^sshd_enable"
    line="sshd_enable=\"YES\""
    backup="yes"
  notify: enable and start sshd
  when: sshd_enable|lower == "yes"
  tags:
    - fp_ssh_rcconf
    - fp_ssh
    - fp_all

- name: Disable and stop sshd
  lineinfile: >
    dest="/etc/rc.conf"
    regexp="^sshd_enable"
    line="sshd_enable=\"NO\""
    backup="yes"
  notify: disable and stop sshd
  when: sshd_enable|lower == "no"
  tags:
    - fp_ssh_rcconf
    - fp_ssh
    - fp_all

# EOF
...
