---

- name: copy default files
  copy: >
    src="{{freebsd_postinstall_copy_dir}}/default/"
    dest="/"
    backup="yes"
  tags: copy

- name: copy IP specific files
  copy: >
    src="{{freebsd_postinstall_copy_dir}}/{{ansible_default_ipv4.address}}/"
    dest="/"
    backup="yes"
  tags: copy

  # BUG: synchronize module does not work
  # TASK [vbotka.ansible-freebsd-postinstall : copy]
  # ******************************* fatal: [...]: FAILED!
  # => {"changed": false, "failed": true, "module_stderr": "sudo: a
  # password is required\n", "module_stdout": "", "msg": "MODULE
  # FAILURE", "parsed": false}
