---

- name: Synchronize default files {{ freebsd_postinstall_copy_dir }}/default (relative to playbooks directory)
  synchronize: >
    src="{{ freebsd_postinstall_copy_dir }}/default/"
    dest="/"
    archive="no"
    recursive="yes"
    times="yes"
    perms="yes"
    checksum="yes"
  tags: freebsd_postinstall_default_copy

- name: Check existence of {{ role_path }}/{{ freebsd_postinstall_copy_dir }}/{{ rc_conf_hostname }}
  local_action: >
    stat path="{{ role_path }}/{{ freebsd_postinstall_copy_dir }}/{{ rc_conf_hostname }}"
  register: optional_copy
  tags: freebsd_postinstall_optional_copy
  # NOTE: playbooks directory IS NOT local_action modules current
  # working directory. Absolute path role_path is needed.

- name: Synchronize host specific files {{ freebsd_postinstall_copy_dir }}/{{ rc_conf_hostname }} (relative to playbooks directory)
  synchronize: >
    src="{{ freebsd_postinstall_copy_dir }}/{{ rc_conf_hostname }}/"
    dest="/"
    archive="no"
    recursive="yes"
    times="yes"
    perms="yes"
    checksum="yes"
  when: optional_copy.stat.exists
  tags: freebsd_postinstall_optional_copy

# EOF
...
