---

- name: "cron: Configure cron variables"
  cronvar:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    user: "{{ item.user }}"
  loop: "{{ fp_cron_var }}"
  tags: fp_cron_var

- name: "cron: Configure cron"
  cron:
    state: "{{ item.state }}"
    user: "{{ item.user }}"
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    day: "{{ item.day }}"
    month: "{{ item.month }}"
    weekday: "{{ item.weekday }}"
    job: "{{ item.command }}"
  loop: "{{ fp_cron_tab }}"
  tags: fp_cron_tab

# TODO: Configure /etc/crontab
# /etc/crontab or crontab -e as root
# https://forums.freebsd.org/threads/etc-crontab-or-crontab-e-as-root.4107/
# 11.3. Configuring cron(8)
# https://www.freebsd.org/doc/handbook/configtuning-cron.html

# EOF
...
