---

- name: "libmap: Configure /etc/libmap.conf"
  lineinfile:
    dest: "/etc/libmap.conf"
    regexp: "^{{ item.origin }} "
    line: "{{ item.origin }} {{ item.target }}"
    backup: yes
  loop: "{{ fp_libmap_entries }}"

# EOF
...
