---
# tasks for vbotka.freebsd-postinstall

- include: config_sysctl.yml
  tags:
    - fp_sysctl
    - fp_all

- include: config_make.yml
  tags:
    - bsd_packages
    - bsd_ports
    - fp_make
    - fp_all

- include: config_swap.yml
  tags:
    - fp_swap
    - fp_all
  when: freebsd_postinstall_swap|lower == "yes"

- include: config_fstab.yml
  tags:
    - fp_fstab
    - fp_all

- include: packages.yml
  tags:
    - bsd_packages
    - bsd_ports
    - fp_packages
    - fp_all

- include: copy.yml
  tags:
    - copy
    - fp_copy
    - fp_all

- include: config_libmap.yml
  tags:
    - fp_config_libmap
    - fp_all

- include: config_users.yml
  tags:
    - fp_users
    - fp_all

- include: groupwrappers.yml
  tags:
    - fp_groupwrappers
    - fp_users
    - fp_all
  when: freebsd_postinstall_groupwrappers_install|lower  == "yes"

- include: config_hostname.yml
  tags:
    - fp_hostname
    - fp_all

- include: config_hosts.yml
  tags:
    - fp_hosts
    - fp_all

- include: config_ssh.yml
  tags:
    - fp_ssh
    - fp_all

- include: config_authorized_key.yml
  tags:
  - fp_authorized_key
  - fp_all

- include: config_timezone.yml
  tags:
    - fp_timezone
    - fp_all

- include: config_ntpd.yml
  tags:
    - fp_ntpd
    - fp_all

- include: config_ntpdate.yml
  tags:
  - fp_ntpdate
  - fp_all

- include: config_nfs.yml
  tags:
    - fp_nfs
    - fp_all

- include: config_nfsd.yml
  tags:
    - fp_nfsd
    - fp_all

- include: config_smartd.yml
  tags:
    - fp_smartd
    - fp_all
  when: freebsd_postinstall_smartd_install|lower == "yes"

- include: config_apcupsd.yml
  tags:
    - fp_apcupsd
    - fp_all
  when: freebsd_postinstall_apcupsd_service_enabled|lower == "yes"

- include: config_hostapd.yml
  tags:
    - fp_hostapd
    - fp_all
  when: freebsd_postinstall_hostapd_install|lower == "yes"

- include: config_procmail.yml
  tags:
    - fp_procmail
    - fp_all
  when: freebsd_postinstall_procmail_install|lower == "yes"

- include: config_motd.yml
  tags:
    - fp_motd
    - fp_all

- debug: msg="{{ freebsd_postinstall_gitserver_install }}"
  tags:
   - fp_gitserver
   - fp_all
  when: freebsd_postinstall_debug|bool == true

- include: config_gitserver.yml
  tags:
    - fp_gitserver
    - fp_all
  when: freebsd_postinstall_gitserver_install|lower == "yes"

# EOF
...
