---
# tasks for freebsd-postinstall

- include: config_fstab.yml
  tags: freebsd_postinstall_fstab, freebsd_postinstall

- include: packages.yml
  tags: freebsd_postinstall_packages, freebsd_postinstall

- include: config_timezone.yml
  tags: freebsd_postinstall_timezone, freebsd_postinstall

- include: config_ntpdate.yml
  tags: freebsd_postinstall_ntpdate, freebsd_postinstall

- include: config_users.yml
  tags: freebsd_postinstall_users, freebsd_postinstall

- include: config_ssh.yml
  tags: freebsd_postinstall_ssh, freebsd_postinstall
