---
# tasks for vbotka.freebsd-postinstall

- name: Debug
  vars:
    msg: |
         ansible_architecture [ {{ ansible_architecture }} ]
         ansible_os_family [ {{ ansible_os_family }} ]
         ansible_distribution [ {{ ansible_distribution }} ]
         ansible_distribution_major_version [ {{ ansible_distribution_major_version }} ]
         ansible_distribution_version [ {{ ansible_distribution_version }} ]
         ansible_distribution_release [ {{ ansible_distribution_release }} ]

         rc_conf_hostname [ {{ rc_conf_hostname }} ]
         fp_domain [ {{ fp_domain }} ]
         fp_zoneinfo [ {{ fp_zoneinfo }} ]
         digitalocean [ {{ digitalocean }} ]
         fp_swap [ {{ fp_swap }} ]
         fp_synchronize_default [ {{ fp_synchronize_default }} ]
         fp_synchronize_optional [ {{ fp_synchronize_optional }} ]
         sshd_enable [ {{ sshd_enable }} ]
         fp_smartd_install [ {{ fp_smartd_install }} ]
         fp_smartd_service_enabled [ {{ fp_smartd_service_enabled }} ]
         fp_apcupsd_install [ {{ fp_apcupsd_install }} ]
         fp_apcupsd_service_enabled [ {{ fp_apcupsd_service_enabled }} ]
         fp_hostapd_install [ {{ fp_hostapd_install }} ]
         fp_hostapd_enabled [ {{ fp_hostapd_enabled }} ]
         fp_nfs_service_enable [ {{ fp_nfs_service_enable }} ]
         fp_nfsd_service_enable [ {{ fp_nfsd_service_enable }} ]
         fp_rpcbind_enable [ {{ fp_rpcbind_enable }} ]
         fp_rpc_lockd_enable [ {{ fp_rpc_lockd_enable }} ]
         fp_rpc_statd_enable [ {{ fp_rpc_statd_enable }} ]
         fp_ntp_service_enable [ {{ fp_ntp_service_enable }} ]
         fp_procmail_install [ {{ fp_procmail_install }} ]
         fp_update_motd [ {{ fp_update_motd }} ]
         fp_groupwrappers_install [ {{ fp_groupwrappers_install }} ]
         fp_gitserver_install [ {{ fp_gitserver_install }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: fp_debug
  tags: fp_debug

- include_tasks: sysctl.yml
  tags: fp_sysctl

- include_tasks: make.yml
  tags: fp_make

- include_tasks: swap.yml
  tags: fp_swap

- include_tasks: fstab.yml
  tags: fp_fstab

- include_tasks: packages.yml
  tags: fp_packages

- include_tasks: copy.yml
  tags: fp_copy

- include_tasks: libmap.yml
  tags: fp_libmap

- include_tasks: users.yml
  tags: fp_users

- include_tasks: groupwrappers.yml
  tags: fp_groupwrappers
  when: fp_groupwrappers_install

- include_tasks: hostname.yml
  tags: fp_hostname

- include_tasks: hosts.yml
  tags: fp_hosts

- include_tasks: ssh.yml
  tags: fp_ssh

- include_tasks: authorized_key.yml
  tags: fp_authorized_key

- include_tasks: timezone.yml
  tags: fp_timezone

- include_tasks: ntpd.yml
  tags: fp_ntpd

- include_tasks: ntpdate.yml
  tags: fp_ntpdate

- include_tasks: nfs.yml
  tags: fp_nfs

- include_tasks: nfsd.yml
  tags: fp_nfsd

- include_tasks: smartd.yml
  tags: fp_smartd
  when: fp_smartd_install

- include_tasks: apcupsd.yml
  tags: fp_apcupsd

- include_tasks: hostapd.yml
  tags: fp_hostapd
  when: fp_hostapd_install

- include_tasks: procmail.yml
  tags: fp_procmail
  when: fp_procmail_install

- include_tasks: motd.yml
  tags: fp_motd

- include_tasks: gitserver.yml
  tags: fp_gitserver
  when: fp_gitserver_install

- include_tasks: sudoers.yml
  tags: fp_sudoers

- include_tasks: loader.yml
  tags: fp_loader

- include_tasks: cron.yml
  tags: fp_cron

# EOF
...
