---
# tasks for vbotka.freebsd-postinstall

- debug: msg="{{ ansible_distribution }} {{ ansible_distribution_major_version }}"
  when: fp_debug|lower == "yes"
  tags:
   - fp_vars
   - fp_all

- name: Print install variables
  vars:
    msg: |
         fp_gitserver_install [ {{ fp_gitserver_install }} ]
         freebsd_postinstall_swap [ {{ freebsd_postinstall_swap }} ]
         freebsd_postinstall_groupwrappers_install [ {{ freebsd_postinstall_groupwrappers_install }} ]
         freebsd_postinstall_smartd_instal install [ {{ freebsd_postinstall_smartd_install }} ]
         freebsd_postinstall_apcupsd_service_enabled [ {{ freebsd_postinstall_apcupsd_service_enabled }} ]
         freebsd_postinstall_hostapd_install [ {{ freebsd_postinstall_hostapd_install }} ]
         freebsd_postinstall_procmail_install [ {{ freebsd_postinstall_procmail_install }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: fp_debug|lower == "yes"
  tags:
   - fp_vars
   - fp_all

- name: Print other variables
  vars:
    msg: |
         fp_zoneinfo [ {{ fp_zoneinfo }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: fp_debug|lower == "yes"
  tags:
   - fp_vars
   - fp_all

- include_tasks: config_sysctl.yml
  tags:
    - fp_sysctl
    - fp_all

- include_tasks: config_make.yml
  tags:
    - bsd_packages
    - bsd_ports
    - fp_make
    - fp_all

- include_tasks: config_swap.yml
  tags:
    - fp_swap
    - fp_all
  when: freebsd_postinstall_swap|lower == "yes"

- include_tasks: config_fstab.yml
  tags:
    - fp_fstab
    - fp_all

- include_tasks: packages.yml
  tags:
    - bsd_packages
    - bsd_ports
    - fp_packages
    - fp_all

- include_tasks: copy.yml
  tags:
    - copy
    - fp_copy
    - fp_all

- include_tasks: config_libmap.yml
  tags:
    - fp_config_libmap
    - fp_all

- include_tasks: config_users.yml
  tags:
    - fp_users
    - fp_all

- include_tasks: groupwrappers.yml
  tags:
    - fp_groupwrappers
    - fp_users
    - fp_all
  when: freebsd_postinstall_groupwrappers_install|lower  == "yes"

- include_tasks: config_hostname.yml
  tags:
    - fp_hostname
    - fp_all

- include_tasks: config_hosts.yml
  tags:
    - fp_hosts
    - fp_all

- include_tasks: config_ssh.yml
  tags:
    - fp_ssh
    - fp_all

- include_tasks: config_authorized_key.yml
  tags:
  - fp_authorized_key
  - fp_all

- include_tasks: config_timezone.yml
  tags:
    - fp_timezone
    - fp_all

- include_tasks: config_ntpd.yml
  tags:
    - fp_ntpd
    - fp_all

- include_tasks: config_ntpdate.yml
  tags:
  - fp_ntpdate
  - fp_all

- include_tasks: config_nfs.yml
  tags:
    - fp_nfs
    - fp_all

- include_tasks: config_nfsd.yml
  tags:
    - fp_nfsd
    - fp_all

- include_tasks: config_smartd.yml
  tags:
    - fp_smartd
    - fp_all
  when: freebsd_postinstall_smartd_install|lower == "yes"

- include_tasks: config_apcupsd.yml
  tags:
    - fp_apcupsd
    - fp_all
  when: freebsd_postinstall_apcupsd_service_enabled|lower == "yes"

- include_tasks: config_hostapd.yml
  tags:
    - fp_hostapd
    - fp_all
  when: freebsd_postinstall_hostapd_install|lower == "yes"

- include_tasks: config_procmail.yml
  tags:
    - fp_procmail
    - fp_all
  when: freebsd_postinstall_procmail_install|lower == "yes"

- include_tasks: config_motd.yml
  tags:
    - fp_motd
    - fp_all

- include_tasks: config_gitserver.yml
  tags:
    - fp_gitserver
    - fp_all
  when: fp_gitserver_install|lower == "yes"

- include_tasks: config_sudoers.yml
  tags:
    - fp_sudoers
    - fp_all

# EOF
...
