---

- name: Install packages
  pkgng: >
    name="{{ item }}"
    state="present"
  with_items: "{{ freebsd_ports }}"
  when: freebsd_install_method|lower == "packages"
  tags: fp_packages

- name: Install ports
  portinstall: >
    name="{{ item }}"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  with_items: "{{ freebsd_ports }}"
  when: freebsd_install_method|lower == "ports"
  tags: fp_ports

# smartmontools
- name: Install smartmontools package
  pkgng: >
    name="sysutils/smartmontools"
    state="present"
  when:
    - freebsd_install_method|lower == "packages"
    - freebsd_postinstall_smartd_install|lower == "yes"
  tags: fp_packages_smartmontools

- name: Install smartmontools port
  portinstall: >
    name="sysutils/smartmontools"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  when:
    - freebsd_install_method|lower == "ports"
    - freebsd_postinstall_smartd_install|lower == "yes"
  tags: fp_ports_smartmontools

# hostapd
- name: Install hostapd package
  pkgng: >
    name="net/hostapd"
    state="present"
  when:
    - freebsd_install_method|lower == "packages"
    - freebsd_postinstall_hostapd_install|lower == "yes"
  tags: fp_packages_hostapd

- name: Install hostapd port
  portinstall: >
    name="net/hostapd"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  when:
    - freebsd_install_method|lower == "ports"
    - freebsd_postinstall_hostapd_install|lower == "yes"
  tags: fp_ports_hostapd

# procmail
- name: Install procmail package
  pkgng: >
    name="mail/procmail"
    state="present"
  when:
    - freebsd_install_method|lower == "packages"
    - freebsd_postinstall_procmail_install|lower == "yes"
  tags: fp_packages_procmail

- name: Install procmail port
  portinstall: >
    name="mail/procmail"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  when:
    - freebsd_install_method|lower == "ports"
    - freebsd_postinstall_procmail_install|lower == "yes"
  tags: fp_ports_procmail

# apcupsd
- name: Install sysutils/apcupsd  package
  pkgng: >
    name="sysutils/apcupsd"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  when:
    - freebsd_install_method|lower == "packages"
    - freebsd_postinstall_apcupsd_service_enabled|lower == "yes"
  tags: fp_packages_apcupsd

- name: Install sysutils/apcupsd  port
  portinstall: >
    name="sysutils/apcupsd"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  when:
    - freebsd_install_method|lower == "ports"
    - freebsd_postinstall_apcupsd_service_enabled|lower == "yes"
  tags: fp_ports_apcupsd

# links
- name: Create symbolic links
  file: >
    src="{{ item.target }}"
    dest="{{ item.link }}"
    state="link"
    force="yes"
  with_items: "{{ freebsd_postinstall_links }}"
  tags: fp_links

# EOF
...
