---

- name: Install packages
  pkgng: >
    name="{{item}}"
    state="present"
  with_items: "{{freebsd_postinstall_packages}}"
  when: freebsd_install_method == "packages"
  tags: packages

- name: Install ports
  portinstall: >
    name="{{item}}"
    state="present"
    use_packages="{{freebsd_use_packages}}"
  with_items: "{{freebsd_postinstall_packages}}"
  when: freebsd_install_method == "ports"
  tags: ports

- name: Install smartmontools package
  pkgng: >
    name="smartmontools"
    state="present"
  when: (freebsd_install_method == "packages") and (freebsd_postinstall_smartd_service_enabled == "yes")
  tags: packages

- name: Install smartmontools port
  portinstall: >
    name="smartmontools"
    state="present"
    use_packages="{{freebsd_use_packages}}"
  when: (freebsd_install_method == "ports") and (freebsd_postinstall_smartd_service_enabled == "yes")
  tags: ports
