---

- name: Install packages
  pkgng: >
    name="{{ item }}"
    state="present"
  with_items: "{{ freebsd_postinstall_packages }}"
  when: freebsd_install_method == "packages"
  tags: freebsd_postinstall_packages

- name: Install ports
  portinstall: >
    name="{{ item }}"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  with_items: "{{ freebsd_postinstall_packages }}"
  when: freebsd_install_method == "ports"
  tags: freebsd_postinstall_ports

- name: Install smartmontools package
  pkgng: >
    name="smartmontools"
    state="present"
  when: (freebsd_install_method == "packages") and (freebsd_postinstall_smartd_install == "YES")
  tags: freebsd_postinstall_packages

- name: Install smartmontools port
  portinstall: >
    name="smartmontools"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  when: (freebsd_install_method == "ports") and (freebsd_postinstall_smartd_install == "YES")
  tags: freebsd_postinstall_ports

- name: Install hostapd package
  pkgng: >
    name="hostapd"
    state="present"
  when: (freebsd_install_method == "packages") and (freebsd_postinstall_hostapd_install == "YES")
  tags: freebsd_postinstall_packages

- name: Install hostapd port
  portinstall: >
    name="hostapd"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  when: (freebsd_install_method == "ports") and (freebsd_postinstall_hostapd_install == "YES")
  tags: freebsd_postinstall_ports

- name: Install procmail package
  pkgng: >
    name="procmail"
    state="present"
  when: (freebsd_install_method == "packages") and (freebsd_postinstall_procmail_install == "YES")
  tags: freebsd_postinstall_packages

- name: Install procmail port
  portinstall: >
    name="procmail"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  when: (freebsd_install_method == "ports") and (freebsd_postinstall_procmail_install == "YES")
  tags: freebsd_postinstall_ports

- name: Create symbolic links
  file: >
    src="{{ item.target }}"
    dest="{{ item.link }}"
    state="link"
    force="yes"
  with_items: "{{ freebsd_postinstall_links }}"
  tags: freebsd_postinstall_links

# EOF
...
