---

- name: "periodic: Debug"
  vars:
    msg: |
         fp_periodic_conf
         {{ fp_periodic_conf_local | to_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"
  when: fp_debug

- name: "periodic_conf: Configure /etc/periodic.conf.local"
  lineinfile:
    dest: "/etc/periodic.conf.local"
    regexp: "^{{ item.regexp }}"
    line: "{{ item.regexp }}{{ item.value }}"
    backup: yes
    create: yes
  loop: "{{ fp_periodic_conf_local }}"

# NOTES:
#
# 13.10. Monitoring Third Party Security Issues
# https://www.freebsd.org/doc/handbook/security-pkg.html
#
# Not Getting Security Reports
# https://forums.freebsd.org/threads/not-getting-security-reports.21841/
#
# Daily security scripts: best practice for jails?
# https://forums.freebsd.org/threads/daily-security-scripts-best-practice-for-jails.55868/

# EOF
...
