---

- name: "sysctl: Debug"
  vars:
    msg: |
         fp_sysctl [
         {{ fp_sysctl | to_nice_yaml }} ]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: fp_debug

- name: "sysctl: Configure /etc/sysctl.conf"
  lineinfile:
    dest: "/etc/sysctl.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "EOF"
    backup: yes
    create: yes
  with_items: "{{ fp_sysctl }}"
  notify: reload sysctl

- meta: flush_handlers

# EOF
...
