---
# handlers for freebsd-postinstall

- name: set hostname
  command: hostname "{{rc_conf_hostname}}"

- name: enable ntpdate
  service: name=ntpdate enabled=yes

- name: disable ntpdate
  service: name=ntpdate enabled=no

# update the local time CMOS clock and kernel machdep.adjkerntz
# variable when timezone changes occur
- name: adjust CMOS
  command: adjkerntz -a

# sshd
- name: enable and start sshd
  service: name="sshd" state="started" enabled="yes"

- name: disable and stop sshd
  service: name="sshd" state="stopped" enabled="no"

- name: restart sshd
  service: name="sshd" state="restarted"

- name: reload sshd
  service: name="sshd" state="reloaded"

- name: mount all
  command: mount -a

- name: create and mount swap
  shell: sh -c 'dd if=/dev/zero of={{freebsd_postinstall_swap_file}} bs=1m count={{freebsd_postinstall_swap_size}}; chmod 0600 {{freebsd_postinstall_swap_file}}; swapon -aL'

- name: change and mount swap
  shell: sh -c 'swapoff /dev/{{freebsd_postinstall_swap_md}}; mdconfig -du {{freebsd_postinstall_swap_md}}; dd if=/dev/zero of={{freebsd_postinstall_swap_file}} bs=1m count={{freebsd_postinstall_swap_size}}; chmod 0600 {{freebsd_postinstall_swap_file}}; swapon -aL'

# EOF
